name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "yhyh4420"
          git config user.email "yhyh4420@naver.com"
          git remote set-url origin https://yhyh4420:${GITHUB_TOKEN}@github.com/yhyh4420/yhyh4420.git

          git pull --rebase origin main
          git add -A .
          git commit -m "generated" || echo "nothing to commit"
          git push origin main
